server:
  port: 8080

spring:
    devtools:
    ## 远程更新 配置的验证秘钥
        remote:
            secret: mysecret
        # 监控文件触发热部署，有变化就执行一次热部署,
        # 先修改完成代码，然后修改reloadtrigger.txt，然后在执行build->build project 或者ctrl+F9
        restart:
          trigger-file: reloadtrigger.txt
          # 默认排除的 "META-INF/maven/**,META-INF/resources/**,resources/**,static/**,public/**,templates/**,**/*Test.class,**/*Tests.class,git.properties,META-INF/build-info.properties"
          additional-exclude: exclude/**
          #监控需要 重启的目录
          additional-paths: include/**
